server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/usuario
        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: trace
            route:
              RouteDefinitionRouteLocator: info
              RoutePredicateHandlerMapping: debug
              RoutePredicateFactory: debug